name: Daily Latest Repacks Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  
  workflow_dispatch:

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v6

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      # 3. Install Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Install Playwright Browsers
      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium

      # 5. Run the Scraper
      - name: Run Scraper Script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python fitgirl_latest_repacks_scraper.py
